### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by laptevn** [deptno/action-aws-ssm-to-dotenv#9]
The following configuration of an action doesn't work
```
- uses: deptno/action-aws-ssm-to-dotenv@v1.3.1
   with:
   ssm-path: /blabla/db_username
   prefix: TF_VAR_
   output: $GITHUB_ENV
   decryption: true
```
It displays a warning "Warning: Unexpected input(s) 'ssm-path', valid inputs are ['ssm-paths', 'format', 'output', 'prefix', 'decryption']"
Trying "ssm-paths" instead of "ssm-path" leads to an error that "ssm-path" is mandatory.

I'm curious if you tested this action before release?
